Previous release accidentally broke Rails 3.2 support - this fixes that.
The bug exposes itself as an error similar to:

[ERROR] io.undertow.request  - Blocking request failed HttpServerExchange{ GET /}
java.lang.UnsupportedOperationException: BUG: invoking UndefinedMethod.call; report at http://bugs.jruby.org
	at org.jruby.internal.runtime.methods.UndefinedMethod.call(UndefinedMethod.java:59)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)
	at org.projectodd.wunderboss.ruby.rack.RackHandler.handleRequest(RackHandler.java:46)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:139)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:638)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)